insert into access_permissions (key, scope, description)
values
	('workspace.operacao.view', 'tenant', 'Visualizar a workspace Operacao.'),
	('workspace.operacao.edit', 'tenant', 'Editar a workspace Operacao.'),
	('workspace.consultor.view', 'tenant', 'Visualizar a workspace Consultor.'),
	('workspace.ranking.view', 'tenant', 'Visualizar a workspace Ranking.'),
	('workspace.dados.view', 'tenant', 'Visualizar a workspace Dados.'),
	('workspace.inteligencia.view', 'tenant', 'Visualizar a workspace Inteligencia.'),
	('workspace.relatorios.view', 'tenant', 'Visualizar a workspace Relatorios.'),
	('workspace.campanhas.view', 'tenant', 'Visualizar a workspace Campanhas.'),
	('workspace.campanhas.edit', 'tenant', 'Editar a workspace Campanhas.'),
	('workspace.multiloja.view', 'tenant', 'Visualizar a workspace Multi-loja.'),
	('workspace.multiloja.edit', 'tenant', 'Editar a workspace Multi-loja.'),
	('workspace.usuarios.view', 'tenant', 'Visualizar a workspace Usuarios.'),
	('workspace.usuarios.edit', 'tenant', 'Editar a workspace Usuarios.'),
	('workspace.configuracoes.view', 'tenant', 'Visualizar a workspace Configuracoes.'),
	('workspace.configuracoes.edit', 'tenant', 'Editar a workspace Configuracoes.'),
	('users.password.manage', 'platform', 'Redefinir senha administrativa pelo painel.'),
	('access.role_defaults.manage', 'platform', 'Editar o acesso padrao por papel.')
on conflict (key) do update
set
	scope = excluded.scope,
	description = excluded.description;

insert into access_role_permissions (role, permission_key)
values
	('consultant', 'workspace.operacao.view'),
	('consultant', 'workspace.operacao.edit'),
	('store_terminal', 'workspace.operacao.view'),
	('store_terminal', 'workspace.operacao.edit'),
	('store_terminal', 'workspace.consultor.view'),
	('store_terminal', 'workspace.ranking.view'),
	('store_terminal', 'workspace.dados.view'),
	('store_terminal', 'workspace.inteligencia.view'),
	('store_terminal', 'workspace.relatorios.view'),
	('manager', 'workspace.operacao.view'),
	('manager', 'workspace.operacao.edit'),
	('marketing', 'workspace.operacao.view'),
	('marketing', 'workspace.campanhas.view'),
	('marketing', 'workspace.campanhas.edit'),
	('director', 'workspace.operacao.view'),
	('owner', 'workspace.operacao.view'),
	('owner', 'workspace.operacao.edit'),
	('owner', 'workspace.consultor.view'),
	('owner', 'workspace.ranking.view'),
	('owner', 'workspace.dados.view'),
	('owner', 'workspace.inteligencia.view'),
	('owner', 'workspace.relatorios.view'),
	('owner', 'workspace.campanhas.view'),
	('owner', 'workspace.campanhas.edit'),
	('owner', 'workspace.multiloja.view'),
	('owner', 'workspace.multiloja.edit'),
	('owner', 'workspace.usuarios.view'),
	('owner', 'workspace.usuarios.edit'),
	('owner', 'workspace.configuracoes.view'),
	('owner', 'workspace.configuracoes.edit'),
	('platform_admin', 'workspace.operacao.view'),
	('platform_admin', 'workspace.operacao.edit'),
	('platform_admin', 'workspace.consultor.view'),
	('platform_admin', 'workspace.ranking.view'),
	('platform_admin', 'workspace.dados.view'),
	('platform_admin', 'workspace.inteligencia.view'),
	('platform_admin', 'workspace.relatorios.view'),
	('platform_admin', 'workspace.campanhas.view'),
	('platform_admin', 'workspace.campanhas.edit'),
	('platform_admin', 'workspace.multiloja.view'),
	('platform_admin', 'workspace.multiloja.edit'),
	('platform_admin', 'workspace.usuarios.view'),
	('platform_admin', 'workspace.usuarios.edit'),
	('platform_admin', 'workspace.configuracoes.view'),
	('platform_admin', 'workspace.configuracoes.edit'),
	('platform_admin', 'users.password.manage'),
	('platform_admin', 'access.role_defaults.manage')
on conflict (role, permission_key) do nothing;