-- 0138 - Reaplica defaults atuais da matriz access_role_permissions.
--
-- Contexto: alguns bancos tinham access_role_permissions divergente do
-- default em back/internal/modules/access/permissions.go. Usuarios novos
-- resolviam permissoes pelo banco e perdiam workspaces como relatorios,
-- ranking/dados/inteligencia e alertas.view, mesmo com role correta.
--
-- Migration aditiva: nao remove permissoes extras nem altera usuarios.

insert into access_permissions (key, scope, description)
values
	('workspace.operacao.view', 'tenant', 'Visualizar a workspace Operacao.'),
	('workspace.operacao.edit', 'tenant', 'Executar comandos na workspace Operacao.'),
	('workspace.consultor.view', 'tenant', 'Visualizar a workspace Consultor.'),
	('workspace.ranking.view', 'tenant', 'Visualizar a workspace Ranking.'),
	('workspace.dados.view', 'tenant', 'Visualizar a workspace Dados.'),
	('workspace.inteligencia.view', 'tenant', 'Visualizar a workspace Inteligencia.'),
	('workspace.relatorios.view', 'tenant', 'Visualizar a workspace Relatorios.'),
	('workspace.campanhas.view', 'tenant', 'Visualizar a workspace Campanhas.'),
	('workspace.campanhas.edit', 'tenant', 'Editar a workspace Campanhas.'),
	('workspace.clientes.view', 'tenant', 'Visualizar a workspace Clientes.'),
	('workspace.clientes.edit', 'tenant', 'Editar clientes e grupos acessiveis.'),
	('workspace.multiloja.view', 'tenant', 'Visualizar a workspace Multi-loja.'),
	('workspace.multiloja.edit', 'tenant', 'Editar lojas e configuracoes administrativas da workspace Multi-loja.'),
	('workspace.usuarios.view', 'tenant', 'Visualizar a workspace Usuarios.'),
	('workspace.usuarios.edit', 'tenant', 'Editar usuarios e overrides de acesso pelo painel.'),
	('workspace.manage.view', 'tenant', 'Visualizar as rotas agrupadas em Manage.'),
	('workspace.configuracoes.view', 'tenant', 'Visualizar a workspace Configuracoes.'),
	('workspace.configuracoes.edit', 'tenant', 'Editar configuracoes operacionais.'),
	('workspace.themes.view', 'tenant', 'Visualizar a workspace Temas.'),
	('workspace.alertas.view', 'tenant', 'Visualizar a workspace Alertas.'),
	('workspace.alertas.edit', 'tenant', 'Gerenciar a workspace Alertas.'),
	('alerts.rules.manage', 'tenant', 'Editar regras tenant-wide do modulo de alertas.'),
	('alerts.actions.manage', 'tenant', 'Executar acknowledge e resolucao de alertas operacionais.'),
	('workspace.feedback.view', 'tenant', 'Visualizar a workspace Feedback.'),
	('workspace.feedback.edit', 'tenant', 'Editar feedback e notas administrativas.'),
	('workspace.tools.view', 'tenant', 'Visualizar a workspace Tools.'),
	('workspace.erp.view', 'tenant', 'Visualizar a workspace ERP.'),
	('workspace.erp.edit', 'tenant', 'Executar sync manual e administrar a workspace ERP.'),
	('users.password.manage', 'platform', 'Redefinir senha administrativa pelo painel.'),
	('access.role_defaults.manage', 'platform', 'Editar o acesso padrao por papel.')
on conflict (key) do update
set
	scope = excluded.scope,
	description = excluded.description;

insert into access_role_permissions (role, permission_key)
values
	('consultant', 'workspace.operacao.view'),
	('consultant', 'workspace.operacao.edit'),
	('store_terminal', 'workspace.operacao.view'),
	('store_terminal', 'workspace.operacao.edit'),
	('store_terminal', 'workspace.consultor.view'),
	('store_terminal', 'workspace.ranking.view'),
	('store_terminal', 'workspace.dados.view'),
	('store_terminal', 'workspace.inteligencia.view'),
	('store_terminal', 'workspace.relatorios.view'),
	('store_terminal', 'workspace.alertas.view'),
	('store_terminal', 'alerts.actions.manage'),
	('manager', 'workspace.operacao.view'),
	('manager', 'workspace.operacao.edit'),
	('manager', 'workspace.alertas.view'),
	('manager', 'alerts.actions.manage'),
	('manager', 'workspace.erp.view'),
	('manager', 'workspace.feedback.view'),
	('manager', 'workspace.feedback.edit'),
	('manager', 'workspace.multiloja.view'),
	('marketing', 'workspace.operacao.view'),
	('marketing', 'workspace.erp.view'),
	('marketing', 'workspace.multiloja.view'),
	('marketing', 'workspace.campanhas.view'),
	('marketing', 'workspace.campanhas.edit'),
	('director', 'workspace.operacao.view'),
	('director', 'workspace.erp.view'),
	('director', 'workspace.multiloja.view'),
	('owner', 'workspace.operacao.view'),
	('owner', 'workspace.operacao.edit'),
	('owner', 'workspace.consultor.view'),
	('owner', 'workspace.ranking.view'),
	('owner', 'workspace.dados.view'),
	('owner', 'workspace.inteligencia.view'),
	('owner', 'workspace.relatorios.view'),
	('owner', 'workspace.campanhas.view'),
	('owner', 'workspace.campanhas.edit'),
	('owner', 'workspace.clientes.view'),
	('owner', 'workspace.clientes.edit'),
	('owner', 'workspace.multiloja.view'),
	('owner', 'workspace.multiloja.edit'),
	('owner', 'workspace.usuarios.view'),
	('owner', 'workspace.usuarios.edit'),
	('owner', 'workspace.manage.view'),
	('owner', 'workspace.configuracoes.view'),
	('owner', 'workspace.configuracoes.edit'),
	('owner', 'workspace.themes.view'),
	('owner', 'workspace.alertas.view'),
	('owner', 'workspace.alertas.edit'),
	('owner', 'alerts.rules.manage'),
	('owner', 'alerts.actions.manage'),
	('owner', 'workspace.feedback.view'),
	('owner', 'workspace.feedback.edit'),
	('owner', 'workspace.tools.view'),
	('owner', 'workspace.erp.view'),
	('owner', 'workspace.erp.edit'),
	('platform_admin', 'workspace.operacao.view'),
	('platform_admin', 'workspace.operacao.edit'),
	('platform_admin', 'workspace.consultor.view'),
	('platform_admin', 'workspace.ranking.view'),
	('platform_admin', 'workspace.dados.view'),
	('platform_admin', 'workspace.inteligencia.view'),
	('platform_admin', 'workspace.relatorios.view'),
	('platform_admin', 'workspace.campanhas.view'),
	('platform_admin', 'workspace.campanhas.edit'),
	('platform_admin', 'workspace.clientes.view'),
	('platform_admin', 'workspace.clientes.edit'),
	('platform_admin', 'workspace.multiloja.view'),
	('platform_admin', 'workspace.multiloja.edit'),
	('platform_admin', 'workspace.usuarios.view'),
	('platform_admin', 'workspace.usuarios.edit'),
	('platform_admin', 'workspace.manage.view'),
	('platform_admin', 'workspace.configuracoes.view'),
	('platform_admin', 'workspace.configuracoes.edit'),
	('platform_admin', 'workspace.themes.view'),
	('platform_admin', 'workspace.alertas.view'),
	('platform_admin', 'workspace.alertas.edit'),
	('platform_admin', 'alerts.rules.manage'),
	('platform_admin', 'alerts.actions.manage'),
	('platform_admin', 'workspace.feedback.view'),
	('platform_admin', 'workspace.feedback.edit'),
	('platform_admin', 'workspace.tools.view'),
	('platform_admin', 'workspace.erp.view'),
	('platform_admin', 'workspace.erp.edit'),
	('platform_admin', 'users.password.manage'),
	('platform_admin', 'access.role_defaults.manage')
on conflict (role, permission_key) do nothing;
