export default {
  moduleId: 'queue',
  sections: [
    {
      id: 'service',
      label: 'Atendimento',
      items: [
        {
          id: 'omnichannel',
          label: 'Omnichannel',
          icon: 'messages',
          path: '/omnichannel',
          hidden: true,
        },
        {
          id: 'tasks',
          label: 'Tasks',
          icon: 'tasks',
          path: '/tasks',
          workspaceId: 'tasks',
          beta: true,
        },
        { id: 'tracking', label: 'Tracking', icon: 'tracking', path: '/tracking', hidden: true },
        { id: 'fila', label: 'Fila', icon: 'queue', path: '/operacao', workspaceId: 'operacao' },
      ],
    },
    {
      id: 'tools',
      label: 'Tools',
      items: [
        {
          id: 'tools-menu',
          label: 'Tools',
          icon: 'tools',
          workspaceId: 'tools',
          children: [
            {
              id: 'editor',
              label: 'Editor',
              icon: 'page',
              path: '/editor',
              workspaceId: 'tools',
              beta: true,
            },
            {
              id: 'qr-code',
              label: 'QR Code',
              icon: 'qr',
              path: '/tools/qr-code',
              workspaceId: 'tools',
              hidden: true,
            },
            {
              id: 'link-shortener',
              label: 'Encurtador de Link',
              icon: 'link',
              path: '/tools/encurtador-de-link',
              workspaceId: 'tools',
              hidden: true,
            },
            {
              id: 'scripts',
              label: 'Scripts',
              icon: 'script',
              path: '/tools/scripts',
              workspaceId: 'tools',
              hidden: true,
            },
          ],
        },
      ],
    },
    {
      id: 'team-site',
      label: 'Operacao comercial',
      hidden: true,
      items: [
        {
          id: 'team-menu',
          label: 'Team',
          icon: 'team',
          children: [
            {
              id: 'consultor',
              label: 'Consultor',
              icon: 'user',
              path: '/consultor',
              workspaceId: 'consultor',
            },
            { id: 'team-equipe', label: 'Equipe', icon: 'team', path: '/team/equipe' },
            { id: 'team-escalas', label: 'Escalas', icon: 'calendar', path: '/team/escalas' },
          ],
        },
        {
          id: 'site-menu',
          label: 'Site',
          icon: 'site',
          children: [
            {
              id: 'campanhas',
              label: 'Campanhas',
              icon: 'megaphone',
              path: '/campanhas',
              workspaceId: 'campanhas',
            },
            { id: 'site-paginas', label: 'Paginas', icon: 'page', path: '/site/paginas' },
            {
              id: 'site-formularios',
              label: 'Formularios',
              icon: 'forms',
              path: '/site/formularios',
            },
          ],
        },
      ],
    },
    {
      id: 'indicators',
      label: 'Indicadores',
      items: [
        {
          id: 'indicadores-menu',
          label: 'Indicadores',
          icon: 'indicators',
          children: [
            {
              id: 'consultor',
              label: 'Consultor',
              icon: 'user',
              path: '/consultor',
              workspaceId: 'consultor',
            },
            {
              id: 'ranking',
              label: 'Ranking',
              icon: 'ranking',
              path: '/ranking',
              workspaceId: 'ranking',
            },
            { id: 'dados', label: 'Dados', icon: 'chart', path: '/dados', workspaceId: 'dados' },
            {
              id: 'inteligencia',
              label: 'Inteligencia',
              icon: 'brain',
              path: '/inteligencia',
              workspaceId: 'inteligencia',
              hidden: true,
            },
            {
              id: 'relatorios',
              label: 'Relatorios',
              icon: 'reports',
              path: '/relatorios',
              workspaceId: 'relatorios',
              hidden: true,
            },
            { id: 'bi', label: 'BI', icon: 'chart', path: '/bi', workspaceId: 'bi', hidden: true },
            { id: 'crm', label: 'CRM', icon: 'chart', path: '/crm', workspaceId: 'crm' },
          ],
        },
        { id: 'finance', label: 'Finance', icon: 'finance', path: '/finance', hidden: true },
        {
          id: 'monitoramento',
          label: 'Monitoramento',
          icon: 'monitoring',
          path: '/monitoramento',
          hidden: true,
        },
      ],
    },
    {
      id: 'manage',
      label: 'Manage',
      items: [
        {
          id: 'manage-menu',
          label: 'Manage',
          icon: 'manage',
          workspaceId: 'manage',
          children: [
            {
              id: 'clientes',
              label: 'Clientes',
              icon: 'building',
              path: '/clientes',
              workspaceId: 'clientes',
            },
            {
              id: 'manage-clientes',
              label: 'Clientes Admin',
              icon: 'manage',
              path: '/manage/clientes',
              workspaceId: 'clientes',
            },
            {
              id: 'usuarios',
              label: 'Usuarios',
              icon: 'users',
              path: '/usuarios',
              workspaceId: 'usuarios',
            },
            {
              id: 'manage-users',
              label: 'Usuarios Admin',
              icon: 'manage_accounts',
              path: '/manage/users',
              workspaceId: 'usuarios',
            },
            { id: 'erp', label: 'ERP', icon: 'boxes', path: '/erp', workspaceId: 'erp' },
            {
              id: 'multiloja',
              label: 'Multi-loja',
              icon: 'stores',
              path: '/multiloja',
              workspaceId: 'multiloja',
            },
            {
              id: 'configuracoes',
              label: 'Config',
              icon: 'settings',
              path: '/configuracoes',
              workspaceId: 'configuracoes',
            },
            {
              id: 'alertas',
              label: 'Alertas',
              icon: 'alert',
              path: '/alertas',
              workspaceId: 'alertas',
            },
            {
              id: 'feedback',
              label: 'Feedback',
              icon: 'feedback',
              path: '/feedback',
              workspaceId: 'feedback',
            },
            {
              id: 'themes',
              label: 'Temas',
              icon: 'palette',
              path: '/themes',
              workspaceId: 'themes',
            },
            { id: 'banco', label: 'Banco', icon: 'database', path: '/banco', workspaceId: 'banco' },
            {
              id: 'manage-auditoria',
              label: 'Auditoria',
              icon: 'audit',
              path: '/manage/auditoria',
              workspaceId: 'manage',
            },
            {
              id: 'manage-integracoes',
              label: 'Integracoes',
              icon: 'integration',
              path: '/manage/integracoes',
              workspaceId: 'manage',
            },
            {
              id: 'roadmap',
              label: 'Roadmap',
              icon: 'indicators',
              path: '/roadmap',
              workspaceId: 'roadmap',
            },
          ],
        },
      ],
    },
  ],
}
