export default {
  moduleId: 'queue',
  sections: [
    {
      id: 'service',
      label: 'Atendimento',
      items: [
        {
          // Gateado como os irmaos (tasks/calendario): workspaceId 'omnichannel'
          // (gate de PAPEL) + moduleId 'omnichannel' (gate de MODULO por conta,
          // core.account_modules, espelhando o back em /v1/omnichannel).
          // `icon` aqui e chave do NAV_ICON_MAP ('messages' -> MessagesSquare) —
          // vocabulario diferente do `icon` do workspaces.ts, que e ligature.
          id: 'omnichannel',
          label: 'Omnichannel',
          icon: 'messages',
          path: '/omnichannel',
          workspaceId: 'omnichannel',
          moduleId: 'omnichannel',
          beta: true,
        },
        {
          id: 'tasks',
          label: 'Tasks',
          icon: 'tasks',
          path: '/tasks',
          workspaceId: 'tasks',
          moduleId: 'tasks',
          beta: true,
        },
        {
          // Gateado como os irmaos (tasks/automation): workspaceId 'calendar'
          // (gate de PAPEL) + moduleId 'calendar' (gate de MODULO por conta,
          // core.account_modules, espelhando o back em /v1/calendar). Some do
          // menu para papel sem o workspace OU conta sem o modulo.
          id: 'calendario',
          label: 'Calendário',
          icon: 'calendar',
          path: '/calendario',
          workspaceId: 'calendar',
          moduleId: 'calendar',
          beta: true,
        },
        {
          id: 'tracking',
          label: 'Tracking',
          icon: 'tracking',
          path: '/tracking',
          workspaceId: 'tasks',
          moduleId: 'tasks',
          beta: true,
        },
        {
          id: 'fila',
          label: 'Fila',
          icon: 'queue',
          path: '/operacao',
          workspaceId: 'operacao',
          moduleId: 'queue',
        },
        {
          id: 'automation',
          label: 'Automacao',
          icon: 'brain',
          path: '/automation',
          workspaceId: 'automation',
          moduleId: 'automation',
          beta: true,
        },
      ],
    },
    {
      id: 'tools',
      label: 'Tools',
      items: [
        {
          id: 'tools-menu',
          label: 'Tools',
          icon: 'tools',
          workspaceId: 'tools',
          children: [
            {
              id: 'editor',
              label: 'Editor',
              icon: 'page',
              path: '/editor',
              workspaceId: 'tools',
              moduleId: 'tools',
              beta: true,
            },
            {
              id: 'qr-code',
              label: 'QR Code',
              icon: 'qr',
              path: '/tools/qr-code',
              workspaceId: 'tools',
              moduleId: 'tools',
            },
            {
              id: 'link-shortener',
              label: 'Encurtador de Link',
              icon: 'link',
              path: '/tools/encurtador-de-link',
              workspaceId: 'tools',
              moduleId: 'tools',
            },
            {
              id: 'scripts',
              label: 'Scripts',
              icon: 'script',
              path: '/tools/scripts',
              workspaceId: 'tools',
              hidden: true,
            },
          ],
        },
      ],
    },
    {
      id: 'team-site',
      label: 'Operacao comercial',
      items: [
        {
          id: 'team-menu',
          label: 'Team',
          icon: 'team',
          hidden: true,
          children: [
            {
              id: 'consultor',
              label: 'Consultor',
              icon: 'user',
              path: '/consultor',
              workspaceId: 'consultor',
              moduleId: 'queue',
            },
            { id: 'team-equipe', label: 'Equipe', icon: 'team', path: '/team/equipe' },
            { id: 'team-escalas', label: 'Escalas', icon: 'calendar', path: '/team/escalas' },
          ],
        },
        {
          id: 'site-menu',
          label: 'Site',
          icon: 'site',
          children: [
            {
              id: 'site-leads',
              label: 'Leads',
              icon: 'feedback',
              path: '/site/leads',
              workspaceId: 'site_leads_web',
              moduleId: 'site',
            },
            {
              id: 'site-produtos',
              label: 'Produtos',
              icon: 'boxes',
              path: '/site/produtos',
              workspaceId: 'site_produtos_web',
              moduleId: 'site',
            },
            {
              id: 'site-tracking',
              label: 'Tracking',
              icon: 'tracking',
              path: '/site/tracking',
              workspaceId: 'site_tracking_web',
              moduleId: 'site',
            },
            {
              id: 'site-bio',
              label: 'Bio',
              icon: 'page',
              path: '/site/bio',
              workspaceId: 'site_bio_web',
              moduleId: 'bio',
              beta: true,
            },
            {
              id: 'campanhas',
              label: 'Campanhas',
              icon: 'megaphone',
              path: '/campanhas',
              workspaceId: 'campanhas',
            },
          ],
        },
        {
          id: 'meta-ads',
          label: 'Meta Ads',
          icon: 'megaphone',
          path: '/meta-ads',
          workspaceId: 'meta_ads',
          moduleId: 'meta_ads',
          beta: true,
        },
        {
          id: 'cardapio',
          label: 'Cardápio Online',
          icon: 'boxes',
          path: '/cardapio',
          workspaceId: 'cardapio_web',
          moduleId: 'cardapio',
          beta: true,
        },
      ],
    },
    {
      id: 'indicators',
      label: 'Indicadores',
      items: [
        {
          id: 'indicadores-menu',
          label: 'Indicadores',
          icon: 'indicators',
          children: [
            {
              id: 'consultor',
              label: 'Consultor',
              icon: 'user',
              path: '/consultor',
              workspaceId: 'consultor',
              moduleId: 'queue',
            },
            {
              id: 'ranking',
              label: 'Ranking',
              icon: 'ranking',
              path: '/ranking',
              workspaceId: 'ranking',
              moduleId: 'queue',
            },
            {
              id: 'dados',
              label: 'Dados',
              icon: 'chart',
              path: '/dados',
              workspaceId: 'dados',
              moduleId: 'queue',
            },
            {
              id: 'inteligencia',
              label: 'Inteligencia',
              icon: 'brain',
              path: '/inteligencia',
              workspaceId: 'inteligencia',
              moduleId: 'queue',
              hidden: true,
            },
            {
              id: 'relatorios',
              label: 'Relatorios',
              icon: 'reports',
              path: '/relatorios',
              workspaceId: 'relatorios',
              moduleId: 'queue',
              hidden: true,
            },
            { id: 'bi', label: 'BI', icon: 'chart', path: '/bi', workspaceId: 'bi', hidden: true },
            {
              id: 'crm',
              label: 'CRM',
              icon: 'chart',
              path: '/crm',
              workspaceId: 'crm',
              moduleId: 'crm',
            },
          ],
        },
        // Finance: gate por modulo + workspace (back real /v1/finance). Some para
        // contas sem o modulo; platform_admin ve via platformView/bypass.
        {
          id: 'finance',
          label: 'Finance',
          icon: 'finance',
          path: '/finance',
          workspaceId: 'finance',
          moduleId: 'finance',
        },
        {
          id: 'monitoramento',
          label: 'Monitoramento',
          icon: 'monitoring',
          path: '/monitoramento',
          hidden: true,
        },
        {
          id: 'performance',
          label: 'Performance',
          icon: 'monitoring',
          path: '/performance',
          workspaceId: 'performance',
        },
      ],
    },
    {
      id: 'manage',
      label: 'Manage',
      items: [
        {
          id: 'manage-menu',
          label: 'Manage',
          icon: 'manage',
          workspaceId: 'manage',
          children: [
            {
              id: 'clientes',
              label: 'Clientes',
              icon: 'building',
              path: '/operacao/clientes',
              workspaceId: 'clientes',
              moduleId: 'queue',
            },
            {
              id: 'manage-clientes',
              label: 'Clientes Admin',
              icon: 'manage',
              path: '/manage/clientes',
              workspaceId: 'clientes',
            },
            {
              id: 'manage-clientes-web',
              label: 'Clientes Web',
              icon: 'manage',
              path: '/manage/clientes-web',
              workspaceId: 'clientes_web',
              agencyOnly: true,
            },
            {
              id: 'manage-produtos-web',
              label: 'Produtos do site',
              icon: 'page',
              path: '/manage/produtos-web',
              workspaceId: 'site_produtos_web',
              moduleId: 'site',
              hidden: true,
            },
            {
              id: 'manage-leads-web',
              label: 'Leads do site',
              icon: 'page',
              path: '/manage/leads-web',
              workspaceId: 'site_leads_web',
              moduleId: 'site',
              hidden: true,
            },
            {
              id: 'usuarios',
              label: 'Usuarios',
              icon: 'users',
              path: '/operacao/usuarios',
              workspaceId: 'usuarios',
              moduleId: 'queue',
            },
            {
              id: 'manage-users',
              label: 'Usuarios Admin',
              icon: 'manage_accounts',
              path: '/manage/users',
              workspaceId: 'usuarios_admin',
              agencyOnly: true,
            },
            {
              id: 'manage-organizations',
              label: 'Organizations',
              icon: 'manage_accounts',
              path: '/manage/organizations',
              workspaceId: 'organizations_admin',
              agencyOnly: true,
            },
            {
              id: 'manage-role-templates',
              label: 'Papeis-padrao',
              icon: 'audit',
              path: '/manage/role-templates',
              workspaceId: 'role_templates_admin',
              agencyOnly: true,
            },
            {
              id: 'erp',
              label: 'ERP',
              icon: 'boxes',
              path: '/erp',
              workspaceId: 'erp',
              moduleId: 'crm',
            },
            {
              id: 'multiloja',
              label: 'Multi-loja',
              icon: 'stores',
              path: '/multiloja',
              workspaceId: 'multiloja',
              moduleId: 'queue',
            },
            {
              id: 'configuracoes',
              label: 'Config',
              icon: 'settings',
              path: '/configuracoes',
              workspaceId: 'configuracoes',
              moduleId: 'queue',
            },
            {
              id: 'menu-layout',
              label: 'Organização do Menu',
              icon: 'manage',
              path: '/manage/menu-layout',
              workspaceId: 'menu_layout',
            },
            {
              id: 'alertas',
              label: 'Alertas',
              icon: 'alert',
              path: '/alertas',
              workspaceId: 'alertas',
              moduleId: 'queue',
            },
            {
              id: 'feedback',
              label: 'Feedback',
              icon: 'feedback',
              path: '/feedback',
              workspaceId: 'feedback',
              moduleId: 'queue',
            },
            {
              id: 'themes',
              label: 'Temas',
              icon: 'palette',
              path: '/themes',
              workspaceId: 'themes',
              agencyOnly: true,
            },
            { id: 'banco', label: 'Banco', icon: 'database', path: '/banco', workspaceId: 'banco' },
            {
              id: 'manage-auditoria',
              label: 'Auditoria',
              icon: 'audit',
              path: '/manage/auditoria',
              workspaceId: 'manage',
              agencyOnly: true,
            },
            {
              id: 'manage-integracoes',
              label: 'Integracoes',
              icon: 'integration',
              path: '/manage/integracoes',
              workspaceId: 'manage',
              agencyOnly: true,
            },
            {
              id: 'roadmap',
              label: 'Roadmap',
              icon: 'indicators',
              path: '/roadmap',
              workspaceId: 'roadmap',
              agencyOnly: true,
            },
          ],
        },
      ],
    },
  ],
}
